# The proposal
*This is where the proposal should be outlined.*

We propose to develop a package that would implement an R Shiny based interface, connecting database of companies (such as MySQL) with R packages and allow users work with the system in an interactive way. The system should be self sufficient and focus on the forecasting side of the business processes. It would allow analysing selected time series and producing forecasts with focuses on specific managerial decisions.

The system itself should be developed in three stages, this proposal outlines only the first of them.

## Overview
*At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.*

The Open Forecast Support System (OFSS) will have two main components:

1. The core, including the main functions for time series analysis and forecasting, using the existing forecasting packages, such as:
    - `tsutils`,
    - `forecast`,
    - `smooth`,
    - `greybox`,
    - `nnfor`,
    - `MAPA`,
    - and others.
2. The interface, accessible via a local area network by users that have necessary privileges.

The system will need to be installed on a stand-alone server, but may also be installed on any computer that has R Shiny server.

The package will be freely available, and any member of the R community would be able to download and set it up for their purposes. Furthermore, the created interface can be adjusted for the needs of any company.

## Detail
*Go into more detail about the specifics of the project and it delivers against the problem.*

*Depending on project type the detail section should include:*

 - [ ] *Minimum Viable Product*
 - [ ] *Architecture*
 - [ ] *Assumptions*

The Core of the OFSS will include the following features:

1.  Data interface between R and SQL, which will allow downloading data from the database and uploading forecasts into it:
    a.  `RMySQL` for MySQL;
    b.  `odbc` and `mssqlR` for MSSQL;
    c.  `RPostgreSQL` for PostgreSQL;
2.	Data analysis:
    a.	Seasonal plots for selected time series using `seasplot()` function from the `tsutils` package;
    b.	Aggregation of data into different cross-sectional groups;
    c.	Aggregation of data into different frequencies (such as daily, weekly, monthly, yearly);
    d.	Decomposition of time series (for the analysis of the residuals), based on `decomp()` function from the `tsutils` package;
3.	Forecasts evaluation:
    a.	Selection and combination of forecasting models for specific level of aggregation based on the state of the art techniques;
    b.	Rolling origin for the selected models with plots of the origins, using `ro()` function from `greybox`;
    c.	Error measures for the point and interval forecasts on different levels of the hierarchy using error measures implemented in `greybox` package;
    d.	Comparison of the accuracy of different models, including the models with the judgmentally adjusted forecasts;
    e.  Analysis of residuals using instruments from `greybox` package.
4.	Forecasting:
    a.	Application of the selected continuous forecasting models based on:
        - `es()`, `ssarima()`, `msarima()`, `ces()`, `sma()` and `ves()` functions from `smooth`,
        - `alm()`, `stepwise()` and `lmCombine()` from `greybox`,
        - `mapa()` from `MAPA`,
        - `thief()` from `thief`,
        - `dotm()` from `forecTheta`,
        - `elm()` and `mlp()` from `nnfor`,
        - `lm()` and `glm()` from `stats` package;
    b.	Application of the selected intermittent demand forecasting models based on:
        - `es()` function from `smooth` package,
        - `alm()` and `stepwise()` from `greybox`;
    c.	Automatic selection / combination of forecasting models. This is implemented in the functions of `greybox`, `smooth`, `forecast`, `MAPA` and `thief` packages;
    d.	Automatic selection of explanatory variables, based on `stepwise()` from `greybox` and LASSO from `glmnet` packages;
    e.	Generation of point and interval forecasts. This is available in many packages and needs to be controlled via `predict()` and `forecast()` methods with the correct parameters, depending on the data type (e.g. mixture distribution models imply more difficult construction of the intervals);
    f.	Grouped time series reconciliation of point and interval forecasts. This is important for a typical business company, because the decisions on different aggregation levels (e.g. strategic and tactical ones) need to agree;

The Interface of the OFSS should include the following features using `shinydashboard` and `shinydashboardPlus` packages:

1.	Dashboard with the forecasts for the most important level and summary of the recent performance of models (i.e. have any outliers happened recently);
2.	Graphical presentation of the Core functions;
3.	Temporal and cross-sectional aggregation level selection;
4.	Start and end dates selection;
5.	Selection of forecast horizon;
6.	Selection of the prediction intervals width and type (parametric / non-parametric etc);
7.	Manual override of the variables included in the model;
8.	Creation of explanatory variables using judgment (i.e. football match and other events, not tractable by the system);
9.	Judgmental modifications of the point and interval forecasts;
10.	Creation of notes, motivating the judgmental adjustments;

The package will have a modular system, allowing to switch on and off different functionality, depending on preferences of the end user.

Given the potential size of the project, it is proposed to do it in several stages:

- Stage 1: (1), (2), (4a) and (4b) from the Core and (2) - (6) from the Interface;
- Stage 2: (3) and (4c) - (4f), from the Core and (1) from the Interface;
- Stage 3: (7) - (10) from the Interface;

This way, in **the first stage** we will create the basic functionality of the system, which will allow producing forecasts for both continuous and intermittent demand and plotting the results; in **the second stage** we will introduce the model selection and combinations, improving the accuracy of forecasts and will implement the dashboard; in **the third stage** we will focus on human-computer interractions and on judgmental corrections of forecasts.

This proposal outlines the work on **the first stage**.